// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrf_2zgiKoMSuphJmjvEGO1_VniGW_vfc',
    appId: '1:72855384303:web:9cd9ffc53436377c38ab1a',
    messagingSenderId: '72855384303',
    projectId: 'store-inventory-sale-manage',
    authDomain: 'store-inventory-sale-manage.firebaseapp.com',
    storageBucket: 'store-inventory-sale-manage.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHYeDK_I6vE7eqZSDeY2Iswt2haiqsNFs',
    appId: '1:72855384303:android:b325854667d6871438ab1a',
    messagingSenderId: '72855384303',
    projectId: 'store-inventory-sale-manage',
    storageBucket: 'store-inventory-sale-manage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQLO4zM93rNYD3Y9qA0PgGjbBQk48VuHk',
    appId: '1:72855384303:ios:eec5a7f3192d9b2938ab1a',
    messagingSenderId: '72855384303',
    projectId: 'store-inventory-sale-manage',
    storageBucket: 'store-inventory-sale-manage.firebasestorage.app',
    iosBundleId: 'com.example.storeApp',
  );
}
